version: "3.9"

services:
  arb-bot:
    image: ${DOCKER_IMAGE}
    container_name: arb-bot
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      RPC_URL: ${RPC_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
    


