version: "3.9"

services:
  arb-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: arb-bot
    restart: unless-stopped
    
    # Optional if you want to run interactively for debugging
    stdin_open: true
    tty: true

  
